name: kira_dashboard
description: "Unofficial KIRA dashboard"
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^7.8.4
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  blockies_svg: ^1.0.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  url_recognizer: ^0.0.2+2
  intl: ^0.19.0
  logger: ^2.0.2+1
  crypto: ^3.0.3
  dio: ^5.4.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  get_it: ^7.6.6
  google_fonts: ^6.1.0
  blockchain_utils: ^1.6.0
  shimmer: ^3.0.0
  bech32: ^0.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  decimal: ^2.3.3
  json_view: ^0.4.2
  countries_world_map: ^1.1.1

  cryptography_utils:
    git:
      url: git@github.com:snggle/cryptography_utils.git
      ref: dp-feature/aesdhke-v1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  auto_route_generator: ^7.3.2
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/

  fonts:
    - family: IconsFont
      fonts:
        - asset: assets/fonts/IconsFont.ttf